### ISSUE TITLE
About SGLI process

### ISSUE THREAD

**Issue by LH002** [DHI-GRAS/seadas-ocssw-scripts#1]
Hello, how can I use l2gen mode to correct the SWIR data of Sgli?

**Comment by j08lue** [comment]
Hey @LH002, this is just an inofficial fork of the original repo. Unfortunately, you will not reach a maintainer or a community here to answer your question. You are welcome to let us know of your findings about what happened to the original one, if you like. Best of luck!

**Comment by lifeodyssey** [comment]
> Hello, how can I use l2gen mode to correct the SWIR data of Sgli?

I have worked with SGLI before. OCSSW does not support SGLI officially.
